### ISSUE TITLE
[BUG] VoxelSniper 8.6.0 doesn't seem to work with MC 1.19.3 and essentialsX

### ISSUE THREAD

**Issue by 91leMAC** [KevinDaGame/VoxelSniper-Reimagined#135] opened 2023-03-25 08:38 UTC
**Describe the bug**
I download the plugin on my spigot server in 1.19.3 and the server doesn't recognize the plugin. (I write /plugins in the console)

**To Reproduce**
1. Download VoxelSniper 8.6.0
2. Put it in the "plugins" folder
3. Restart the server
4. lunch "/plugins"
5. See that there aren't Voxel Sniper there

**Expected behavior**
I want to have voxel sniper in my server
**Screenshots**
![image](https://user-images.githubusercontent.com/89730221/227706778-8dc21a55-3193-40a8-8abd-121b7b162365.png)

**Desktop (please complete the following information):**
 - Minecraft version: 1.19.3
 - Voxelsniper version: 8.6.0
 - Server/client software: Spigot

**Comment by KevinDaGame** [comment] 2023-03-25 08:43
Hi, could you send along your server's log file? It should be in the logs directory under the name latest.log. This will help us diagnose the issue

**Comment by 91leMAC** [comment] 2023-03-25 08:53
> 

`[08:22:24] [Server thread/ERROR]: Could not load 'plugins/voxelsniper-8.6.0-spigot.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:178) ~[spigot-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:144) ~[spigot-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.loadPlugins(CraftServer.java:428) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3669-Spigot-454acb7-f150cfb]
	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:219) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3669-Spigot-454acb7-f150cfb]
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:973) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3669-Spigot-454acb7-f150cfb]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:301) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3669-Spigot-454acb7-f150cfb]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.util.zip.ZipException: zip END header not found
	at java.util.zip.ZipFile$Source.findEND(ZipFile.java:1469) ~[?:?]
	at java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1477) ~[?:?]
	at java.util.zip.ZipFile$Source.<init>(ZipFile.java:1315) ~[?:?]
	at java.util.zip.ZipFile$Source.get(ZipFile.java:1277) ~[?:?]
	at java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:709) ~[?:?]
	at java.util.zip.ZipFile.<init>(ZipFile.java:243) ~[?:?]
	at java.util.zip.ZipFile.<init>(ZipFile.java:172) ~[?:?]
	at java.util.jar.JarFile.<init>(JarFile.java:347) ~[?:?]
	at java.util.jar.JarFile.<init>(JarFile.java:318) ~[?:?]
	at java.util.jar.JarFile.<init>(JarFile.java:284) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:166) ~[spigot-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	... 6 more
[08:22:25] [Server thread/WARN]: Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
[08:22:34] [Server thread/WARN]: Legacy plugin FlySpeed v2.1.0 does not specify an api-version.
[08:22:34] [Server thread/WARN]: Legacy plugin CustomHeads v3.0.7 does not specify an api-version.
[08:22:34] [Server thread/INFO]: [ServerBackup] Loading ServerBackup v2.9.4
[08:22:34] [Server thread/INFO]: [WorldEdit] Loading WorldEdit v7.2.13+46576cc
[08:22:35] [Server thread/INFO]: Got request to register class com.sk89q.worldedit.bukkit.BukkitServerInterface with WorldEdit [com.sk89q.worldedit.extension.platform.PlatformManager@5317c2b8]
[08:22:35] [Server thread/INFO]: [FlySpeed] Loading FlySpeed v2.1.0
[08:22:35] [Server thread/INFO]: [Essentials] Loading Essentials v2.20.0-dev+44-43d84de
[08:22:35] [Server thread/INFO]: [CustomHeads] Loading CustomHeads v3.0.7
[08:22:35] [Server thread/INFO]: [WorldEdit] Enabling WorldEdit v7.2.13+46576cc
[08:22:35] [Server thread/INFO]: Registering commands with com.sk89q.worldedit.bukkit.BukkitServerInterface
[08:22:35] [Server thread/INFO]: WEPIF: Using the Bukkit Permissions API.
[08:22:35] [Server thread/INFO]: Using com.sk89q.worldedit.bukkit.adapter.impl.v1_19_R2.PaperweightAdapter as the Bukkit adapter
[08:22:37] [Server thread/INFO]: [WorldEdit] ====================================================
[08:22:37] [Server thread/INFO]: [WorldEdit]  WorldEdit works better if you use Paper 
[08:22:37] [Server thread/INFO]: [WorldEdit]  as your server software. 
[08:22:37] [Server thread/INFO]: [WorldEdit]   
[08:22:37] [Server thread/INFO]: [WorldEdit]  Paper offers significant performance improvements,
[08:22:37] [Server thread/INFO]: [WorldEdit]  bug fixes, security enhancements and optional
[08:22:37] [Server thread/INFO]: [WorldEdit]  features for server owners to enhance their server.
[08:22:37] [Server thread/INFO]: [WorldEdit]   
[08:22:37] [Server thread/INFO]: [WorldEdit]  Paper includes Timings v2, which is significantly
[08:22:37] [Server thread/INFO]: [WorldEdit]  better at diagnosing lag problems over v1.
[08:22:37] [Server thread/INFO]: [WorldEdit]   
[08:22:37] [Server thread/INFO]: [WorldEdit]  All of your plugins should still work, and the
[08:22:37] [Server thread/INFO]: [WorldEdit]  Paper community will gladly help you fix any issues.
[08:22:37] [Server thread/INFO]: [WorldEdit]   
[08:22:37] [Server thread/INFO]: [WorldEdit]  Join the Paper Community @ https://papermc.io
[08:22:37] [Server thread/INFO]: [WorldEdit] ====================================================
[08:22:37] [Server thread/INFO]: Preparing level "world"
[08:22:37] [Server thread/INFO]: -------- World Settings For [world] --------
[08:22:37] [Server thread/INFO]: Mob Spawn Range: 6
[08:22:37] [Server thread/INFO]: Experience Merge Radius: 3.0
[08:22:37] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313 Ocean: 14357621 Shipwreck: 165745295 End City: 10387313 Slime: 987234911 Nether: 30084232 Mansion: 10387319 Fossil: 14357921 Portal: 34222645
[08:22:37] [Server thread/INFO]: Max TNT Explosions: 100
[08:22:37] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[08:22:37] [Server thread/INFO]: Cactus Growth Modifier: 100%
[08:22:37] [Server thread/INFO]: Cane Growth Modifier: 100%
[08:22:37] [Server thread/INFO]: Melon Growth Modifier: 100%
[08:22:37] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[08:22:37] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[08:22:37] [Server thread/INFO]: Sapling Growth Modifier: 100%
[08:22:37] [Server thread/INFO]: Beetroot Growth Modifier: 100%
[08:22:37] [Server thread/INFO]: Carrot Growth Modifier: 100%
[08:22:37] [Server thread/INFO]: Potato Growth Modifier: 100%
[08:22:37] [Server thread/INFO]: Wheat Growth Modifier: 100%
[08:22:37] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[08:22:37] [Server thread/INFO]: Vine Growth Modifier: 100%
[08:22:37] [Server thread/INFO]: Cocoa Growth Modifier: 100%
[08:22:37] [Server thread/INFO]: Bamboo Growth Modifier: 100%
[08:22:37] [Server thread/INFO]: SweetBerry Growth Modifier: 100%
[08:22:37] [Server thread/INFO]: Kelp Growth Modifier: 100%
[08:22:37] [Server thread/INFO]: TwistingVines Growth Modifier: 100%
[08:22:37] [Server thread/INFO]: WeepingVines Growth Modifier: 100%
[08:22:37] [Server thread/INFO]: CaveVines Growth Modifier: 100%
[08:22:37] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Ra 48 / Mi 16 / Tiv true / Isa false
[08:22:37] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[08:22:37] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1 Hopper Can Load Chunks: false
[08:22:37] [Server thread/INFO]: Item Merge Radius: 2.5
[08:22:37] [Server thread/INFO]: Item Despawn Rate: 6000
[08:22:37] [Server thread/INFO]: View Distance: 10
[08:22:37] [Server thread/INFO]: Simulation Distance: 10
[08:22:37] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[08:22:37] [Server thread/INFO]: Arrow Despawn Rate: 1200 Trident Respawn Rate:1200
[08:22:37] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[08:22:37] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[08:22:38] [Server thread/INFO]: -------- World Settings For [world_nether] --------
[08:22:38] [Server thread/INFO]: Mob Spawn Range: 6
[08:22:38] [Server thread/INFO]: Experience Merge Radius: 3.0
[08:22:38] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313 Ocean: 14357621 Shipwreck: 165745295 End City: 10387313 Slime: 987234911 Nether: 30084232 Mansion: 10387319 Fossil: 14357921 Portal: 34222645
[08:22:38] [Server thread/INFO]: Max TNT Explosions: 100
[08:22:38] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[08:22:38] [Server thread/INFO]: Cactus Growth Modifier: 100%
[08:22:38] [Server thread/INFO]: Cane Growth Modifier: 100%
[08:22:38] [Server thread/INFO]: Melon Growth Modifier: 100%
[08:22:38] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[08:22:38] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[08:22:38] [Server thread/INFO]: Sapling Growth Modifier: 100%
[08:22:38] [Server thread/INFO]: Beetroot Growth Modifier: 100%
[08:22:38] [Server thread/INFO]: Carrot Growth Modifier: 100%
[08:22:38] [Server thread/INFO]: Potato Growth Modifier: 100%
[08:22:38] [Server thread/INFO]: Wheat Growth Modifier: 100%
[08:22:38] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[08:22:38] [Server thread/INFO]: Vine Growth Modifier: 100%
[08:22:38] [Server thread/INFO]: Cocoa Growth Modifier: 100%
[08:22:38] [Server thread/INFO]: Bamboo Growth Modifier: 100%
[08:22:38] [Server thread/INFO]: SweetBerry Growth Modifier: 100%
[08:22:38] [Server thread/INFO]: Kelp Growth Modifier: 100%
[08:22:38] [Server thread/INFO]: TwistingVines Growth Modifier: 100%
[08:22:38] [Server thread/INFO]: WeepingVines Growth Modifier: 100%
[08:22:38] [Server thread/INFO]: CaveVines Growth Modifier: 100%
[08:22:38] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Ra 48 / Mi 16 / Tiv true / Isa false
[08:22:38] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[08:22:38] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1 Hopper Can Load Chunks: false
[08:22:38] [Server thread/INFO]: Item Merge Radius: 2.5
[08:22:38] [Server thread/INFO]: Item Despawn Rate: 6000
[08:22:38] [Server thread/INFO]: View Distance: 10
[08:22:38] [Server thread/INFO]: Simulation Distance: 10
[08:22:38] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[08:22:38] [Server thread/INFO]: Arrow Despawn Rate: 1200 Trident Respawn Rate:1200
[08:22:38] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[08:22:38] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[08:22:38] [Server thread/INFO]: -------- World Settings For [world_the_end] --------
[08:22:38] [Server thread/INFO]: Mob Spawn Range: 6
[08:22:38] [Server thread/INFO]: Experience Merge Radius: 3.0
[08:22:38] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313 Ocean: 14357621 Shipwreck: 165745295 End City: 10387313 Slime: 987234911 Nether: 30084232 Mansion: 10387319 Fossil: 14357921 Portal: 34222645
[08:22:38] [Server thread/INFO]: Max TNT Explosions: 100
[08:22:38] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[08:22:38] [Server thread/INFO]: Cactus Growth Modifier: 100%
[08:22:38] [Server thread/INFO]: Cane Growth Modifier: 100%
[08:22:38] [Server thread/INFO]: Melon Growth Modifier: 100%
[08:22:38] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[08:22:38] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[08:22:38] [Server thread/INFO]: Sapling Growth Modifier: 100%
[08:22:38] [Server thread/INFO]: Beetroot Growth Modifier: 100%
[08:22:38] [Server thread/INFO]: Carrot Growth Modifier: 100%
[08:22:38] [Server thread/INFO]: Potato Growth Modifier: 100%
[08:22:38] [Server thread/INFO]: Wheat Growth Modifier: 100%
[08:22:38] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[08:22:38] [Server thread/INFO]: Vine Growth Modifier: 100%
[08:22:38] [Server thread/INFO]: Cocoa Growth Modifier: 100%
[08:22:38] [Server thread/INFO]: Bamboo Growth Modifier: 100%
[08:22:38] [Server thread/INFO]: SweetBerry Growth Modifier: 100%
[08:22:38] [Server thread/INFO]: Kelp Growth Modifier: 100%
[08:22:38] [Server thread/INFO]: TwistingVines Growth Modifier: 100%
[08:22:38] [Server thread/INFO]: WeepingVines Growth Modifier: 100%
[08:22:38] [Server thread/INFO]: CaveVines Growth Modifier: 100%
[08:22:38] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Ra 48 / Mi 16 / Tiv true / Isa false
[08:22:38] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[08:22:38] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1 Hopper Can Load Chunks: false
[08:22:38] [Server thread/INFO]: Item Merge Radius: 2.5
[08:22:38] [Server thread/INFO]: Item Despawn Rate: 6000
[08:22:38] [Server thread/INFO]: View Distance: 10
[08:22:38] [Server thread/INFO]: Simulation Distance: 10
[08:22:38] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[08:22:38] [Server thread/INFO]: Arrow Despawn Rate: 1200 Trident Respawn Rate:1200
[08:22:38] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[08:22:38] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[08:22:38] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[08:22:45] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[08:22:45] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[08:22:45] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[08:22:45] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[08:22:45] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[08:22:45] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[08:22:45] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[08:22:45] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[08:22:45] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[08:22:45] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[08:22:45] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[08:22:45] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[08:22:45] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[08:22:45] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[08:22:45] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[08:22:45] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[08:22:46] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[08:22:46] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[08:22:47] [Worker-Main-1/INFO]: Preparing spawn area: 18%
[08:22:48] [Worker-Main-1/INFO]: Preparing spawn area: 51%
[08:22:48] [Worker-Main-1/INFO]: Preparing spawn area: 63%
[08:22:48] [Server thread/INFO]: Time elapsed: 10379 ms
[08:22:48] [Server thread/INFO]: Preparing start region for dimension minecraft:the_nether
[08:22:53] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[08:22:53] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[08:22:53] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[08:22:53] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[08:22:53] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[08:22:53] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[08:22:53] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[08:22:53] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[08:22:53] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[08:22:53] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[08:22:53] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[08:22:54] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[08:22:54] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[08:22:55] [Worker-Main-1/INFO]: Preparing spawn area: 34%
[08:22:55] [Server thread/INFO]: Time elapsed: 6779 ms
[08:22:55] [Server thread/INFO]: Preparing start region for dimension minecraft:the_end
[08:22:58] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[08:22:58] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[08:22:58] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[08:22:58] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[08:22:58] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[08:22:58] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[08:22:58] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[08:22:59] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[08:22:59] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[08:22:59] [Server thread/INFO]: Time elapsed: 4322 ms
[08:22:59] [Server thread/INFO]: [ServerBackup] Enabling ServerBackup v2.9.4
[08:23:00] [Server thread/INFO]: [ServerBackup] ServerBackup: Plugin enabled.
[08:23:00] [Server thread/INFO]: [ServerBackup] ServerBackup: Searching for updates...
[08:23:00] [Server thread/INFO]: [FlySpeed] Enabling FlySpeed v2.1.0
[08:23:00] [Server thread/INFO]: [Essentials] Enabling Essentials v2.20.0-dev+44-43d84de
[08:23:00] [Server thread/INFO]: You are running a server with limited API functionality. EssentialsX will still work, but certain features may be disabled.
[08:23:00] [Server thread/INFO]: Attempting to convert old kits in config.yml to new kits.yml
[08:23:00] [Server thread/INFO]: No kits found to migrate.
[08:23:00] [Server thread/INFO]: Loaded 38132 items from items.json.
[08:23:00] [Server thread/INFO]: Using locale en_US
[08:23:00] [Server thread/INFO]: ServerListPingEvent: Spigot iterator API
[08:23:00] [Server thread/INFO]: Starting Metrics. Opt-out using the global bStats config.
[08:23:00] [Server thread/INFO]: Using superperms-based permissions.
[08:23:00] [Server thread/INFO]: [CustomHeads] Enabling CustomHeads v3.0.7
[08:23:00] [Server thread/INFO]: [CustomHeads] Using LATEST as Version Handler
[08:23:00] [Server thread/INFO]: [0;37;22m[[0;33;1mCustomHeads[0;37;22m] [0;33;1mWarning [0;37;22m: [0;33;1mHrm. Seems like CustomHeads wasn't tested on this Minecraft Version (v1_19_R2) yet...[m
[08:23:00] [Server thread/INFO]: [0;37;22m[[0;33;1mCustomHeads[0;37;22m] [0;33;1mWarning [0;37;22m: [0;33;1mFeel free to join my Discord to know when it gets updated[m
[08:23:01] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[08:23:01] [Server thread/INFO]: Done (24.215s)! For help, type "help"
[08:23:01] [Craft Scheduler Thread - 1/INFO]: §6Fetching version information...
[08:23:02] [Craft Scheduler Thread - 0/INFO]: [ServerBackup] ServerBackup: No updates found. The server is running the latest version.
[08:23:02] [Craft Scheduler Thread - 1/WARN]: §4You're §c1 §4EssentialsX dev build(s) out of date!
[08:23:02] [Craft Scheduler Thread - 1/WARN]: §4Download it here:§c https://essentialsx.net/downloads.html
[08:23:04] [User Authenticator #1/INFO]: UUID of player 90leMAC is f2b5e2f0-a2d9-40da-b1b0-53da7c857b6b
[08:23:05] [Server thread/INFO]: 90leMAC joined the game
[08:23:05] [Server thread/INFO]: 90leMAC[/90.27.158.136:50805] logged in with entity id 42 at ([world]212.68733818242058, 68.25675070131723, 531.9531927860866)
[08:24:10] [Server thread/INFO]: 90leMAC issued server command: /plugins
[08:26:52] [Server thread/INFO]: Plugins (5): [0;32;1mServerBackup[0;37;1m, [0;32;1mWorldEdit[0;37;1m, [0;32;1mFlySpeed[0;37;1m, [0;32;1mEssentials[0;37;1m, [0;32;1mCustomHeads[m
[08:36:40] [Server thread/INFO]: 90leMAC issued server command: /plugins
[08:50:01] [Server thread/INFO]: 90leMAC issued server command: /sell list
[08:50:08] [Server thread/INFO]: 90leMAC issued server command: /sell inventory
[08:50:08] [Server thread/INFO]: §e90leMAC §asold§e cobblestone§a for §e$1 §a(1 items at $1 each).
[08:50:08] [Server thread/INFO]: §e90leMAC §asold§e cobblestone_stairs§a for §e$1.50 §a(1 items at $1.50 each).
[08:50:08] [Server thread/INFO]: §e90leMAC §asold§e lever§a for §e$1 §a(1 items at $1 each).
[08:50:29] [Server thread/INFO]: 90leMAC issued server command: //sel list
[08:50:46] [Server thread/INFO]: 90leMAC issued server command: //sel convex
[08:51:06] [Server thread/INFO]: 90leMAC issued server command: //replace stone
[08:51:20] [Server thread/INFO]: 90leMAC issued server command: //undo
[08:51:23] [Server thread/INFO]: 90leMAC issued server command: //sel
[08:51:33] [Server thread/INFO]: 90leMAC issued server command: //sel cuboid
[08:51:37] [Server thread/INFO]: 90leMAC issued server command: //sel
`

**Comment by 91leMAC** [comment] 2023-03-25 08:54
> Hi, could you send along your server's log file? It should be in the logs directory under the name latest.log. This will help us diagnose the issue

https://hastebin.com/share/cefereyoyu.makefile

**Comment by KevinDaGame** [comment] 2023-03-25 09:15
I am unable to reproduce this issue on spigot 1.19.3 using the jar from our downloads page. Could you send over the exact voxelsniper jar you are using, also, please send the output of the command `/version`

**Comment by 91leMAC** [comment] 2023-03-25 10:48
voxelsniper 8.6.0-spigot

[10:47:00] [Server thread/INFO]: This server is running CraftBukkit version 3669-Spigot-454acb7-f150cfb (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT)

**Comment by 91leMAC** [comment] 2023-03-25 13:01
I remove essentials X and it's work.

**Comment by KevinDaGame** [comment] 2023-03-25 13:17
Since I am unable to reproduce this issue, I don't think this is an issue with VoxelSniper Reimagined. I recommend you update all other plugins to try and find the exact problem. Also try running a combination of plugins on a test server. Also make sure you redownload the jar from our downloads, it's not impossible that your jar somehow corrupted

**Comment by 91leMAC** [comment] 2023-03-25 13:28
Ok I'll be try later

**Comment by KevinDaGame** [comment] 2023-03-25 22:40
Closing for now. Please reopen if you have more information

**Closed by KevinDaGame** 2023-03-25 22:40 UTC
Labels: bug
